[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

# Metadata ====================================================================
[project]
name = "pyxu"
dynamic = ["version"]
description = "Modular and scalable computational imaging in Python with support for GPU/out-of-core computing."
readme = "README.rst"
requires-python = ">= 3.9, < 3.12"
license = "MIT"
authors = [
    { name = "M. Simeoni" },
    { name = "S. Kashani" },
    { name = "J. Rué-Queralt" },
    { name = "Pyxu Developers" },
    { name = "", email = "contact@pyxu.org" },
]
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
urls.download = "https://github.com/matthieumeo/pyxu"
urls.homepage = "https://pyxu-org.github.io/"
dependencies = [
    "dask[array,diagnostics,distributed] >= 2023.7, < 2023.12",
    "numba >= 0.57, < 1",
    "numpy >= 1.24, < 2",
    "packaging >= 23.1",
    "scipy >= 1.11, < 2",
    "sparse >= 0.14, < 1",
]

# Optional dependencies =======================================================
[project.optional-dependencies]
dev = [
    "graphviz >= 0.20, < 1",
    "hatch >= 1.7, < 2",
    "ipython >= 8.14, < 9",
    "matplotlib >= 3.7, < 4",
    "nbsphinx  >= 0.9.0, < 1",
    "pre-commit >= 3.3, < 4",
    "pydata_sphinx_theme == 0.13.3",
    "pytest >= 7.4, < 8",
    "scikit-image >= 0.21, < 1",
    "sphinx >= 7.2, < 8",
    "sphinx_codeautolink >= 0.15.0, < 1",
    "sphinx_copybutton >= 0.5.2, < 1",
    "sphinx_design >= 0.4.1, < 1",
    "sphinx_togglebutton >= 0.3.2, < 1",
    "sphinx-gallery >= 0.14.0, < 1",
    "tox >= 4.6, < 5",
]
fft = [ "finufft >= 2.1, < 3", ]
gpu-base = [ "cupy-cuda12x", ]
complete-cpu = [ "pyxu[fft]", ]
complete = [ "pyxu[complete-cpu,gpu-base]", ]


# Get version info from Git ===================================================
[tool.hatch.version]
source = "vcs"

# sdist/wheel config ==========================================================
[tool.hatch.build]
exclude = [
    "/dev",
    "/doc",
    "/src/pyxu_tests",
]
include = [
    "/src",
]
packages = [
    "src/pyxu",
]
